version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/kill_container.sh
      timeout: 300
      runas: root
